# Generated by Django 6.0.2 on 2026-03-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('nome_contato', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('rua', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=255)),
                ('plano', models.CharField(choices=[('basico', 'Básico (2 profissional)'), ('equipe_pequena', 'Equipe Pequena (5 profissionais)'), ('equipe_media', 'Equipe Média (15 profissionais)'), ('equipe_grande', 'Equipe Grande (30)')], default='basico', max_length=20)),
                ('max_profissionais', models.IntegerField(default=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('trial_inicio', models.DateTimeField(auto_now_add=True)),
                ('trial_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('profissionais_cadastrados', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profissionais/')),
                ('ativo', models.BooleanField(default=True)),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.salao')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.salao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('dono', 'Dono'), ('profissional', 'Profissional'), ('cliente', 'Cliente')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('salao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salao')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DiaFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('ativo', models.BooleanField(default=False)),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fim', models.TimeField(default='18:00')),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_funcionamento', to='core.salao')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('salao', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_execucao', models.PositiveBigIntegerField(help_text='Tempo estimado em minutos')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cortes/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='core.salao')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('salao', 'nome')},
            },
        ),
    ]
