# Generated by Django 6.0.2 on 2026-02-24 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('nome_contato', models.CharField(max_length=200)),
                ('plano', models.CharField(choices=[('basico', 'Básico (1 profissional)'), ('equipe_pequena', 'Equipe Pequena (2-5 profissionais)'), ('equipe_media', 'Equipe Média (6-15 profissionais)'), ('equipe_grande', 'Equipe Grande (+15 profissionais)')], default='basico', max_length=20)),
                ('max_profissionais', models.IntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('trial_start', models.DateTimeField(auto_now_add=True)),
                ('trial_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('profissionais_cadastrados', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.salon')),
            ],
        ),
    ]
