# Generated by Django 6.0.2 on 2026-02-24 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='salon',
        ),
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('nome_contato', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('plano', models.CharField(choices=[('basico', 'Básico (1 profissional)'), ('equipe_pequena', 'Equipe Pequena (2-5 profissionais)'), ('equipe_media', 'Equipe Média (6-15 profissionais)'), ('equipe_grande', 'Equipe Grande (+15 profissionais)')], default='basico', max_length=20)),
                ('max_profissionais', models.IntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('trial_inicio', models.DateTimeField(auto_now_add=True)),
                ('trial_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('profissionais_cadastrados', models.IntegerField(default=0)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='salao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.salao'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
    ]
