# Generated by Django 6.0.2 on 2026-02-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profissional_salon_salao_profissional_salao_and_more'),
    ]

    operations = [
    ]
