# Generated by Django 6.0.2 on 2026-02-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260224_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='salao',
            name='senha_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='salao',
            name='tipo_usuario',
            field=models.CharField(choices=[('dono', 'Dono do Salão'), ('cliente', 'Cliente'), ('funcionario', 'Funcionário')], default='cliente', max_length=20),
        ),
    ]
