# Generated by Django 6.0.2 on 2026-02-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salao_senha_hash_salao_tipo_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salao',
            unique_together={('email',)},
        ),
    ]
