# Generated by Django 6.0.2 on 2026-02-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_salao_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salao',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='salao',
            name='senha_hash',
        ),
        migrations.RemoveField(
            model_name='salao',
            name='tipo_usuario',
        ),
    ]
