# Generated by Django 6.0.2 on 2026-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_salao_unique_together_remove_salao_dono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salao',
            name='senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
