# Generated by Django 6.0.2 on 2026-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_salao_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
