# Generated by Django 6.0.2 on 2026-02-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fim', models.TimeField(default='18:00')),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_funcionamento', to='core.salao')),
            ],
            options={
                'unique_together': {('salao', 'dia_semana')},
            },
        ),
    ]
