# Generated by Django 6.0.2 on 2026-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_diafuncionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diafuncionamento',
            name='horario_fim',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AlterField(
            model_name='diafuncionamento',
            name='horario_inicio',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
