# Generated by Django 6.0.2 on 2026-02-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_diafuncionamento_horario_fim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diafuncionamento',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='diafuncionamento',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diafuncionamento',
            name='horario_fim',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='diafuncionamento',
            name='horario_inicio',
            field=models.TimeField(default='08:00'),
        ),
    ]
