# Generated by Django 6.0.2 on 2026-02-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_diafuncionamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_execucao', models.PositiveBigIntegerField(help_text='Tempo estimado em minutos')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cortes/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='core.salao')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('salao', 'nome')},
            },
        ),
    ]
