# Generated by Django 6.0.2 on 2026-02-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salao',
            name='plano',
            field=models.CharField(choices=[('basico', 'Básico (1 profissional)'), ('equipe_pequena', 'Equipe Pequena (5 profissionais)'), ('equipe_media', 'Equipe Média (15 profissionais)'), ('equipe_grande', 'Equipe Grande (30)')], default='basico', max_length=20),
        ),
    ]
