# Generated by Django 6.0.2 on 2026-02-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_salao_max_profissionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salao',
            name='max_profissionais',
            field=models.IntegerField(default=2),
        ),
    ]
