# Generated by Django 6.0.2 on 2026-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_salao_max_profissionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='salao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salao',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salao',
            name='rua',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
