# Generated by Django 6.0.2 on 2026-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_salao_bairro_salao_cep_salao_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='salao',
            name='numero',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
